
test_size: 0.3
random_state: 243153
merge: id

rm_variables: ["id","mobiLoansScore","probability"]

grid_params_lr:
  C: [1.0]
  dual: [False]
  fit_intercept: [True,False]
  intercept_scaling: [1]
  l1_ratio: [None]
  max_iter: [100,250,500]
  multi_class: ['auto']
  n_jobs: [-1]
  penalty: ['none']
  random_state: [243153]
  solver: ['newton-cg','lbfgs','sag','saga']
  tol: [0.0001]
  verbose: [0]
  warm_start: [False]

grid_params_ridge:
  alpha: [1.0]
  copy_X: [True,False]
  fit_intercept: [True,False]
  max_iter: [100,250,500]
  normalize: ['deprecated']
  positive: [True,False]
  random_state: [243153]
  solver: ['auto']
  tol: [0.001]